### ISSUE TITLE
Crash when assigning to path

### ISSUE THREAD

**Issue by markov2** [sysread/URI-Fast#45]
Running 0.53, with this code:
```perl
        if($url->path =~ /[^\x20-\x7f]/)
        {   my $path = $url->path =~ s!([^\x20-\xf0])!$b = $1; utf8::encode($b);
                 join '', map sprintf("%%%02X", ord), split //, $b!gre;
            $url->path($path);
        }
```
I attempt to convert utf8 within the path into hex encoding.  When running this on many urls, I get a crash.  When I remove the storage line (the last one), it does not crash.  It produces various internal checks of malloc.  It may be memory issue on the html_url itself, because this causes a crash with me:
```perl
use warnings;
use strict;
use utf8;

use URI::Fast qw(html_url);

my $url = html_url("/mp3poisk/Relax, take it easy..ιlιlι.. ßѴҎ☺..", "http://mp3prima.com/");
warn "Parsed\n";
warn "Strinigfied: $url\n";

my $path = $url->path =~ s!([^\x20-\xf0])!$b = $1; utf8::encode($b);
                 join '', map sprintf("%%%02X", ord), split //, $b!gre;
warn "To hex=$path\n";

$url->path($path);
warn "Becomes $url\n";
```
I hope the utf8 copy-pastes correctly.

Are you using the right function to determine the length of the input strings?

**Comment by sysread** [comment]
This should be fixed in 849120e. Could you pull the latest master and confirm?

**Comment by markov2** [comment]
I still get a crash in the malloc library.  Again while handling a UTF8 url (now a different one). The actual breaking parameters may not this one...
```perl
my $rel = 'https://i2.wp.com/kono1.jp/wp-content/uploads/2014/09/鞍馬の火祭4001.jpg?resize=604%2C408,';
my $base = 'http://kono1.jp/festival/festival5507';
my $url = html_url $rel, $base;
```
In run the above login in a huge loop.  Running it on a single set, it does not crash, which is a pity: hard to reproduce errors are harder to fix. I do not get a crash when I do not set the path() in my main loop, however... there is a good chance it is related.

The problem with character-sets on the return of host() is over.  When successful IDN conversion, it is stored via `$url->host)`, which does not crash during my test run with thousands of those.

**Comment by sysread** [comment]
That's very strange, because this works and achieves the desired effect:

```
use strict;
use warnings;
use utf8;
use ExtUtils::testlib;
use URI::Fast qw(html_url);

my $rel  = 'https://i2.wp.com/kono1.jp/wp-content/uploads/2014/09/鞍馬の火祭4001.jpg?resize=604%2C408,';
my $base = 'http://kono1.jp/festival/festival5507';
my $url  = html_url $rel, $base;

my $path = $url->path;
$url->path($path);

print "$url\n";
```

That does not mean the bug doesn't exist, just that I'm confused about why we would get a malloc error like that from the setter. I assume the error you are getting is the same as I am:

```
free(): invalid next size (fast)                                                                           
Aborted (core dumped)
```

I _think_ that suggests that the setter is not allocating a large enough buffer. This is the setter:

```
#define URI_SIMPLE_SETTER(member, allowed) \                                                                                                                     
static void set_##member(pTHX_ SV *sv_uri, SV *sv_value) { \                                                                                                     
  uri_t *uri = URI(sv_uri); \                                                                                                                                    
  if (is_defined(aTHX_ sv_value)) { \                                                                                                                            
    size_t len_value, len_enc; \                                                                                                                                 
    const char *value = SvPV_const(sv_value, len_value); \                                                                                                       
    char enc[len_value * 3 + 1]; \                                                                                                                               
    len_enc = uri_encode(value, len_value, enc, allowed, uri->is_iri); \                                                                                         
    str_set(aTHX_ uri->member, enc, len_enc); \                                                                                                                  
  } \                                                                                                                                                            
  else { \                                                                                                                                                       
    str_clear(aTHX_ uri->member); \                                                                                                                              
  } \                                                                                                                                                            
}
 ```

`SvPV_const` is returning the length in bytes, so 3x+1 should be exactly enough bytes to cover the case where every byte must be encoded after null-terminating the string.

So this is weird to me. I'm able to reproduce it consistently when setting the path with the output of your regex in your first example, though.

**Comment by sysread** [comment]
Ugh, I figured it out, I think. `normalize` is creating a `uri_str_t` with a chunk size based on the length of the path string, rather than using the aligned `URI_SIZE_path`. After making that change, I was unable to reproduce, but I am just looping over the utf8 urls you have provided in this thread over and over. I'll push the change, then can you confirm whether it works against your test set?

**Comment by markov2** [comment]
Ran with a few hundred thousand links without crash!!!

My current code is
```perl
        $url = html_url $href, $base;

        if(my $port = $url->port) {
            # not validated nor normalized by URI::Fast
            $port =~ m/^[0-9]{1,8}$/ or return ();  # illegal ports
            $url->port(undef)                       # default ports
                if $port == ($scheme eq 'http' ? 80 : 432);
        }

        # Fix missing path encoding. See xt/benchmark_utf8.t
        if($url->path =~ /[^\x20-\x7f]/)
        {   my $path = $url->path =~ s!([^\x20-\xf0])!$b = $1; utf8::encode($b);
                 join '', map sprintf("%%%02X", ord), split //, $b!gre;
            $url->path($path);
        }

        # Fix missing IDN encoding
        if($url->host =~ /[^\x20-\x7f]/)     # html_url has removed % encoding
        {   my $host = $url->host;
            my $rc;
            my $host2 = idn2_lookup_u8(encode_utf8($host), IDN2_NFC_INPUT, $rc);
            $host2 or warn idn2_strerror_name($rc);
            $host2 or return ();   # invalid idn
            $url->host($host2);
        }
    }
```
So: I add port validation/normalization, utf8 in path -> hex, and utf8 in host -> IDN.

**Comment by sysread** [comment]
FYI, using `URI::Fast::encode` to encode the path would be _much_ faster.

```
$url->path( URI::Fast::encode( scalar $uri->path ) );
```

**Comment by sysread** [comment]
Closing. I just pushed the fix for this to cpan in v0.54.

**Comment by markov2** [comment]
Your suggestion only wins when I add a condition; mallocs are more time consuming than running some complex perl code.
```perl
        $url->path(URI::Fast::encode(scalar $url->path))
               if $url->path =~ /[^\x20-\x7f]/;
```
The benchmark shows that 10 million calls "your way" take 8.49 seconds, where my version needs 15.55.  A considerable gain, but maybe less than you expect.  Perl uses many tricks to avoid expensive mallocs.

**Comment by markov2** [comment]
I take back my enthousiasm: your code encodes all '/' in the path.

**Comment by sysread** [comment]
Heh. Try `raw_path`. I think that sets without encoding.

**Comment by sysread** [comment]
Ugh, ok, that's just a getter. So you'd have to split the path and pass it as a list to get URI::Fast to do it. I'll post a comment in the other ticket and add raw setters there.
